# Generated by Django 6.0.3 on 2026-04-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0002_fix_gerador_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='turmas.turma')),
            ],
            options={
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RealizacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('realizada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes_tarefas', to='alunos.aluno')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='tarefas.tarefa')),
            ],
            options={
                'unique_together': {('tarefa', 'aluno')},
            },
        ),
    ]
