# Generated by Django 6.0.3 on 2026-04-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realizacaotarefa",
            options={
                "verbose_name": "Realização de Tarefa",
                "verbose_name_plural": "Realizações de Tarefas",
            },
        ),
        migrations.AlterModelOptions(
            name="tarefa",
            options={
                "ordering": ["ordem", "criado_em"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
    ]
