# Generated by Django 6.0.3 on 2026-03-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoGeracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "modo",
                    models.CharField(
                        choices=[("rco", "Material RCO"), ("livre", "Material Livre")],
                        default="rco",
                        max_length=10,
                    ),
                ),
                ("num_aulas", models.IntegerField(default=1)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("tecnico", "Técnico"),
                            ("superior", "Superior"),
                            ("eja", "EJA"),
                        ],
                        default="tecnico",
                        max_length=20,
                    ),
                ),
                (
                    "foco",
                    models.CharField(
                        choices=[
                            ("equilibrado", "Equilibrado"),
                            ("teorico", "Mais teórico"),
                            ("pratico", "Mais prático"),
                        ],
                        default="equilibrado",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Claude Sonnet"),
                            ("gemini", "Gemini 2.5 Pro"),
                            ("gpt4o", "GPT-4o"),
                        ],
                        default="claude",
                        max_length=30,
                    ),
                ),
                ("instrucoes", models.TextField(blank=True)),
                ("planejamento", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("planejando", "Planejando"),
                            ("gerando", "Gerando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("tokens_usados", models.IntegerField(default=0)),
                (
                    "custo_estimado",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_geracao",
                        to="turmas.turma",
                        verbose_name="Turma/Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Geração",
                "verbose_name_plural": "Sessões de Geração",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="MaterialEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("pptx", "PPTX"),
                            ("docx", "DOCX"),
                            ("url", "URL"),
                            ("texto", "Texto livre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "papel_rco",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slides", "Slides"),
                            ("atividade", "Atividade"),
                            ("pratica", "Prática"),
                            ("outro", "Outro"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("arquivo", models.FileField(blank=True, upload_to="gerador/inputs/")),
                ("url", models.URLField(blank=True)),
                ("texto_livre", models.TextField(blank=True)),
                ("conteudo_extraido", models.TextField(blank=True)),
                ("ordem", models.IntegerField(default=0)),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="gerador.sessaogeracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material de Entrada",
                "verbose_name_plural": "Materiais de Entrada",
                "ordering": ["ordem"],
            },
        ),
    ]
