# Generated by Django 6.0.3 on 2026-03-16 16:28

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aulas", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF / Slides"),
                            ("zip", "Arquivo ZIP / Código"),
                            ("markdown", "Conteúdo Markdown/HTML"),
                            ("link", "Link Externo"),
                            ("arquivo", "Outro Arquivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "visibilidade",
                    models.CharField(
                        choices=[
                            ("publico", "Público (link da turma)"),
                            ("restrito", "Restrito (requer login Google)"),
                        ],
                        default="publico",
                        max_length=20,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="materiais/%Y/%m/"
                    ),
                ),
                ("url_externa", models.URLField(blank=True)),
                ("conteudo_md", markdownx.models.MarkdownxField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiais",
                        to="aulas.aula",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiais",
                "ordering": ["ordem", "criado_em"],
            },
        ),
    ]
