# Generated by Django 6.0.3 on 2026-04-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF / Slides"),
                    ("zip", "Arquivo ZIP / Código"),
                    ("markdown", "Conteúdo Markdown/HTML"),
                    ("link", "Link Externo"),
                    ("arquivo", "Outro Arquivo"),
                    ("html", "Apostila HTML Estática"),
                ],
                max_length=20,
            ),
        ),
    ]
