# Generated by Django 6.0.3 on 2026-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_drop_classroom_orphan'),
        ('materiais', '0002_alter_material_tipo'),
        ('turmas', '0003_drop_orphan_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='conteudo_html',
            field=models.TextField(blank=True, help_text='HTML estático renderizado do GitHub. Preenchido pela sync do GitHub.'),
        ),
        migrations.AddField(
            model_name='material',
            name='origem_github',
            field=models.CharField(blank=True, db_index=True, help_text='Path do arquivo no repositório GitHub (chave idempotente da sync).', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('origem_github__gt', '')), fields=('turma', 'origem_github'), name='material_unique_por_origem_github'),
        ),
    ]
