# Generated by Django 6.0.3 on 2026-03-16 16:40

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
        ("aulas", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", markdownx.models.MarkdownxField()),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[
                            ("arquivo", "Envio de Arquivo"),
                            ("texto", "Texto / Resposta"),
                            ("link", "Link (GitHub, Replit...)"),
                        ],
                        default="arquivo",
                        max_length=20,
                    ),
                ),
                ("prazo", models.DateTimeField()),
                (
                    "valor_pontos",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("permitir_reenvio", models.BooleanField(default=True)),
                ("publicada", models.BooleanField(default=True)),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aulas.aula",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["-prazo", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("entregue", "Entregue"),
                            ("atrasada", "Entregue em Atraso"),
                            ("avaliada", "Avaliada"),
                        ],
                        default="entregue",
                        max_length=20,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="entregas/%Y/%m/"
                    ),
                ),
                ("texto", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("data_avaliacao", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="atividades.atividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["-data_envio"],
                "unique_together": {("atividade", "aluno")},
            },
        ),
    ]
