# Generated by Django 6.0.3 on 2026-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='prazo_extendido',
            field=models.DateTimeField(blank=True, help_text='Prazo individual para este aluno. Se preenchido, substitui o prazo geral da atividade.', null=True),
        ),
    ]
