# Generated by Django 6.0.3 on 2026-03-17 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0002_add_prazo_extendido_entrega"),
        ("aulas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="aula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="aulas.aula",
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("entregue", "Entregue"),
                    ("atrasada", "Entregue em Atraso"),
                    ("avaliada", "Avaliada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
