# Generated by Django 6.0.3 on 2026-04-17 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_atividade_conteudo_html_origem_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
