# Generated by Django 6.0.3 on 2026-03-16 02:40

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=300)),
                ("numero", models.PositiveIntegerField()),
                ("data", models.DateField(blank=True, null=True)),
                ("conteudo", markdownx.models.MarkdownxField(blank=True)),
                ("realizada", models.BooleanField(default=False)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["ordem", "numero"],
                "unique_together": {("turma", "numero")},
            },
        ),
    ]
