# Generated by Django 6.0.3 on 2026-04-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="imagem_capa",
            field=models.ImageField(
                blank=True,
                upload_to="aulas/capas/%Y/%m/",
                verbose_name="Imagem de capa",
            ),
        ),
    ]
