# Generated by Django 6.0.6 on 2026-06-03 23:50

from django.db import migrations, models


def migrar_status(apps, schema_editor):
    """Popula o campo status com base no campo realizada existente."""
    Aula = apps.get_model("aulas", "Aula")
    Aula.objects.filter(realizada=True).update(status="publicada")
    Aula.objects.filter(realizada=False).update(status="rascunho")


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0004_aula_gera_apostila"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("publicada", "Publicada"),
                    ("arquivada", "Arquivada"),
                ],
                default="rascunho",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrar_status, migrations.RunPython.noop),
    ]
