# Generated by Django 6.0.3 on 2026-03-16 02:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data_entrada", models.DateField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["aluno__nome"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("periodo", models.CharField(max_length=20)),
                ("ano_letivo", models.IntegerField()),
                (
                    "token_publico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "alunos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="turmas",
                        through="turmas.Matricula",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["-ano_letivo", "nome"],
            },
        ),
        migrations.AddField(
            model_name="matricula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matriculas",
                to="turmas.turma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={("aluno", "turma")},
        ),
    ]
